var StylesDomain={
  status:styleStatus,
  source:styleSource,
  isOpen:isOpenStyle,
  isSupplierShowroom:isSupplierShowroomStyle,
  supplierReference:styleSupplierReference,
  fabricReference:styleFabricReference,
  lifecycleMetadata:styleLifecycleMetadata,
  collections:styleCollectionNames,
  brandCollectionMap:styleBrandCollectionMapFromNotes,
  fromNegotiationRow:styleFromNegotiationRow,
  normalizeNegotiationRows:normalizeNegotiationRowsAsStyles,
  selectRows:selectNegotiationRowsForStyles,
  creation:{
    createdByTypes:STYLE_CREATED_BY_TYPES,
    lifecycleStates:STYLE_LIFECYCLE_STATES,
    publicationStates:STYLE_PUBLICATION_STATES,
    myStylesTabs:MY_STYLES_TABS,
    normalizeCreatedByType:normalizeStyleCreatedByType,
    canonicalFromNegotiationRow:canonicalStyleFromNegotiationRow,
    myStylesTabForStyle:myStylesTabForCanonicalStyle,
    supplierCanPublishToExplore:supplierStyleCanPublishToExplore,
    createBrandContext:createBrandStyleContextModel,
    validateBrandContext:validateBrandStyleContextModel,
    brandCanSeeContext:brandCanSeeBrandStyleContextModel,
    createRepository:typeof createStyleCreationRepository==='function'?createStyleCreationRepository:null,
    service:typeof StyleCreationService==='object'?StyleCreationService:null,
    createRfq:createStyleRfqModel,
    createQuotation:createStyleQuotationModel,
    confirmedOutcomeClosesCanonicalStyle:confirmedOutcomeClosesCanonicalStyleModel
  }
};
